#!/bin/sh

uci -q set system.@system[0].hostname='theultimate-ax3000t'
uci -q commit system

uci -q set network.globals='globals'
uci -q set network.globals.packet_steering='1'
uci -q commit network

exit 0
