#!/bin/sh

uci -q set system.@system[0].hostname='theultimate-r5s'
uci -q commit system

uci -q set network.globals='globals'
uci -q set network.globals.packet_steering='1'
uci -q commit network

if [ -x /etc/init.d/irqbalance ]; then
    /etc/init.d/irqbalance enable
fi

exit 0
